name: Matrix Workflow

on:
  push:
    branches:
      - main

jobs:
  visualize:
    runs-on: ${{ matrix.os }} # Change 'run-on' to 'runs-on'

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
        browser: [chrome, firefox, safari]

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} # Fix formatting of 'node-version'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run visualization script
        run: node visualize.js

      - name: Run browser tests
        run: npm test --browser=${{ matrix.browser }} # Fix formatting of 'browser'
